baseurl = "https://mjbright.github.io"
title = ""
copyright = "&copy; 2016 Mike Bright"
languageCode = "en-us"
theme = "academic"
enableEmoji = true

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""


[params]
  name = "Mike Bright"
  role = "Solution Architect"
  organization = "HPE (Hewlett-Packard Enterprise)"
  avatar = "Mike_4_Chili_Constitucion.smaller.cropped.png"
  email = "mjbrightfr AT gmail.com"
  address = "5 ave Raymond Chanas, 38053 Grenoble Cedex 9, FRANCE"
  phone = "+33 67299 1647"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  #[[params.social]]
  #  icon = "envelope"
  #  icon_pack = "fa"
  #  link = "mailto:test@example.org"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "http://www.linkedin.com/in/mjbright"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "http:////twitter.com/mjbright"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "http:////twitter.com/pyuggre"

  #[[params.social]]
  #  icon = "google-scholar"
  #  icon_pack = "ai"
  #  link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/mjbright"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Conferences"
  url = "#publications"
  weight = 2

[[menu.main]]
  name = "[Blogspot]"
  url = "http://mjbright.blogspot.fr/"
  weight = 3

[[menu.main]]
  name = "[Grenoble Python UG]"
  url = "http://mjbright.github.io/Pygre"
  weight = 4

[[menu.main]]
  name = "[Python Meetups]"
  url = "http://www.meetup.com/Groupe-dutilisateurs-Python-Grenoble/"
  weight = 5

[[menu.main]]
  name = "[Docker Meetups]"
  url = "http://www.meetup.com/Docker-Grenoble/"
  weight = 6

[[menu.main]]
  name = "[FOSS Meetups]"
  url = "http://www.meetup.com/FLOSS-Grenoble/"
  weight = 7

#[[menu.main]]
  #name = "Projects"
  #url = "#projects"
  #weight = 4

#[[menu.main]]
#  name = "Teaching"
#  url = "#teaching"
#  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 10
